# PyTorch 基本运算示例
Torch的tensor和Numpy的Array，Pandas的Series和Dataframe类似，是了解应用这些代码库的基础，这里首先简单快速地了解Tensor及如何使用GPU，然后日常积累一些常用张量运算函数。

主要参考：

- TENSORS
- Speed Up your Algorithms Part 1 — PyTorch
- PyTorch 101, Part 1: Understanding Graphs, Automatic Differentiation and Autograd

# 快速了解Tensor

pytorch作为NumPy的替代品，可以利用GPU的性能进行计算；可作为一个高灵活性、速度快的深度学习平台。

Tensor（张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。因此经常看到把numpy的数组包装为tensor再运算。tensor的操作和numpy中的数组操作类似，不再赘述，详见官网。下面列举一些简单例子。首先pytorch的导入是import torch，因为torch一直都是那个torch，一开始是别的语言写的，现在在python下，所以就叫pytorch。

In [1]:
import torch

Tensor是pytorch的基本数据类型：

In [2]:
x = torch.Tensor(5)
# 如果想要从tensor中获取到长度的int数据
type(list(x.shape)[0])

int

In [3]:
# 构建一个 5x3 的矩阵, 未初始化的:
x = torch.Tensor(5, 3)
x

tensor([[6.4805e-10, 6.3008e-10, 6.6376e-07],
        [6.7211e-04, 6.7742e-10, 4.4150e-05],
        [6.4097e-10, 1.4580e-19, 1.1495e+24],
        [3.0956e-18, 1.5099e-07, 1.7063e-07],
        [1.0243e-11, 1.7490e-04, 1.3444e+22]])

pytorch中的一些基本运算：

In [4]:
# 构建一个随机初始化的矩阵:
x = torch.rand(5, 3)
x

tensor([[0.2233, 0.7761, 0.2564],
        [0.5790, 0.4550, 0.4087],
        [0.7997, 0.5478, 0.0184],
        [0.7594, 0.4024, 0.8799],
        [0.8194, 0.1312, 0.1601]])

In [5]:
x.size()

torch.Size([5, 3])

concatenate的操作使用torch.cat可以完成

In [6]:
x1 = torch.Tensor(1)
x2 = torch.Tensor(1)
torch.cat((x1,x2),0)

tensor([-6.9205e-07,  2.9289e-15])

可以看到torch中的size也是torch中的类，包装了python的list，自然地，加减运算的对象也都是torch的tensor了。运算可以使用运算符，也可以使用函数。

In [7]:
# 加法
y = torch.rand(5, 3)
x + y

tensor([[0.9311, 0.8211, 0.9142],
        [1.2674, 0.7522, 1.2235],
        [1.6389, 0.5619, 0.0822],
        [0.7935, 0.4396, 0.9509],
        [1.3783, 0.4231, 0.4452]])

In [8]:
torch.add(x, y)

tensor([[0.9311, 0.8211, 0.9142],
        [1.2674, 0.7522, 1.2235],
        [1.6389, 0.5619, 0.0822],
        [0.7935, 0.4396, 0.9509],
        [1.3783, 0.4231, 0.4452]])

In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)

tensor([[0.9311, 0.8211, 0.9142],
        [1.2674, 0.7522, 1.2235],
        [1.6389, 0.5619, 0.0822],
        [0.7935, 0.4396, 0.9509],
        [1.3783, 0.4231, 0.4452]])

In [10]:
a = torch.ones(5)
a.add_(1)

tensor([2., 2., 2., 2., 2.])

numpy和tensor之间有很多类似的地方，比如索引，形状改变等：

In [11]:
# 可以用类似Numpy的索引来处理所有的张量！
x[:, 1]

tensor([0.7761, 0.4550, 0.5478, 0.4024, 0.1312])

In [12]:
# 改变大小: 如果你想要去改变tensor的大小, 可以使用 torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1就是让pytorch自己根据其他的维度去判断这里该是几维
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.0689, -1.3366,  0.1422,  0.0287],
        [ 0.7963,  0.7980,  0.8254,  0.4380],
        [-0.6162,  1.6615, -0.6046, -0.7127],
        [ 0.4745, -1.1442,  0.6496,  1.7060]])
tensor([-0.0689, -1.3366,  0.1422,  0.0287,  0.7963,  0.7980,  0.8254,  0.4380,
        -0.6162,  1.6615, -0.6046, -0.7127,  0.4745, -1.1442,  0.6496,  1.7060])
tensor([[-0.0689, -1.3366,  0.1422,  0.0287,  0.7963,  0.7980,  0.8254,  0.4380],
        [-0.6162,  1.6615, -0.6046, -0.7127,  0.4745, -1.1442,  0.6496,  1.7060]])


由于和numpy的紧密联系，因此pytorch的张量和numpy数组可以很方便的转换。

In [13]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

要注意numpy的array和torch的tensor转换后，数据是绑定的，如下所示：

In [15]:
# 看改变 np 数组之后 Torch Tensor 是如何自动改变的
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print("numpy的array：",a)
print("array转为torch的tensor：",b)
np.add(a, 1, out = a)
print(a)
print(b)

numpy的array： [1. 1. 1. 1. 1.]
array转为torch的tensor： tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
# 可以使用 .cuda 方法将 Tensors 在GPU上运行.
# 只要在  CUDA 是可用的情况下, 我们可以运行这段代码
if torch.cuda.is_available():
    b = b.cuda()
    print(b + b)

tensor([4., 4., 4., 4., 4.], device='cuda:0', dtype=torch.float64)


CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换。

张量要在GPU上计算，需要主动从CPU移动到GPU上。张量可以使用.to方法移动到任何设备（device）上

In [17]:
x = torch.randn(1)
print(x)
print(x.item())
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([-0.5152])
-0.5151782035827637
tensor([0.4848], device='cuda:0')
tensor([0.4848], dtype=torch.float64)


## GPU or CPU
检查 cuda 设备是否可用：

In [18]:
import torch
torch.cuda.is_available()

True

In [19]:
# 如果有GPU的话 可以执行下面几个注释掉的代码
# torch.cuda.current_device()

In [20]:
# torch.cuda.get_device_name(0)

In [21]:
# Returns the current GPU memory usage by tensors in bytes for a given device
# torch.cuda.memory_allocated()

In [22]:
# Returns the current GPU memory managed by the caching allocator in bytes for a given device
# torch.cuda.memory_reserved()

In [23]:
# Releases all unoccupied cached memory currently held by the caching allocator so that those can be used in other GPU application and visible in nvidia-smi
# torch.cuda.empty_cache()

如何使用GPU？

如果像存储数据到CPU，那么简单定义即可：

In [24]:
a = torch.DoubleTensor([1., 2.])

这时候变量在CPU上，且后续的运算都会在CPU上，为了将数据转移到GPU上，需要使用 .cuda

In [25]:
# a = torch.FloatTensor([1., 2.]).cuda()

或者

In [26]:
# a = torch.cuda.FloatTensor([1., 2.])

这时候数据就在GPU上。模型同样可以转移到GPU上，比如：

In [27]:
from torch import nn
model = nn.Sequential(
         nn.Linear(20, 20),
         nn.ReLU(),
         nn.Linear(20, 4),
         nn.Softmax()
)
# model = model.cuda()

检查在不在GPU上。

In [28]:
next(model.parameters()).is_cuda

False

如果有多个GPU，可以使用Data Parallelism，拆分数据，将 Data Generator 拆分到更小的mini batches，然后送到多个GPUs

PyTorch中，并行通过torch.nn.DataParallel实现。一些关键函数：：

- Replicate：Module在多个设备上复制。
- Scatter：input在这些设备的第一维中分布。
- Gather：从这些设备收集input和连接第一维。
- parallel_apply：将从Scatter获得的一组输入分布式应用于从Replicate获得的相应的分布式Modules。

或者一种更简单的方式：

model = nn.DataParallel(model, device_ids=device_ids)
result = model(input)

更多信息可以关注：

- Multi-GPU Framework Comparisons
- ilkarman/DeepLearningFrameworks
下面是Tensor的常见计算，日常积累。

# 基本算术运算
Tensor是一种数据结构，是 PyTorch 的基本构建块。Tensors 非常像 numpy 数组，与 numpy 不同的是，张量旨在利用 GPU 的并行计算能力。许多 Tensor 语法类似于 numpy 数组的语法。

In [29]:
import numpy as np
import torch

## 初始化
直接调用Tensor即可完成初始化。

In [30]:
tt = torch.Tensor(3)

和numpy不同的是，为了完成梯度下降等优化计算，Tensor还有梯度相关的属性（后续文本会有更多介绍），初始化时候requires_grad默认是False

In [31]:
tt.requires_grad

False

初始化为0

In [32]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

Tensor

In [33]:
t_one = torch.ones(4)
t_one.requires_grad

False

requires_grad具有传染性。这意味着当通过对其他Tensors运算创建一个Tensor，且其中至少有一个用于创建的张量requires_grad被设置为True时，运算结果Tensor的requires_grad也将被设置为True。

In [34]:
a = torch.randn((3,3), requires_grad = True)
w1 = torch.randn((3,3))
b = w1*a 
b.requires_grad

True

如果想要计算后的张量不被前序变量传染，可以使用detach()（非inplace运算），先detach()再计算即可。

In [35]:
b_detach = w1*(a.detach())
b_detach == b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [36]:
b_detach.requires_grad

False

detach()不是inplace运算，所以a还是有requires_grad的。

In [37]:
a.requires_grad

True

## 均值计算

In [38]:
X = np.random.rand(6,4)
print(X,X.shape)
avg_np, _ = np.average(X, axis=0, returned=True)
avg_np, _

[[0.52146413 0.36520019 0.90335486 0.93659799]
 [0.95935638 0.74781084 0.46586094 0.32297474]
 [0.91883664 0.06089713 0.06050851 0.64880174]
 [0.27150115 0.72627856 0.14427034 0.14566632]
 [0.67025999 0.65209428 0.40618876 0.64416075]
 [0.4553301  0.35495258 0.50411814 0.02562346]] (6, 4)


(array([0.6327914 , 0.48453893, 0.41405026, 0.45397083]),
 array([6., 6., 6., 6.]))

In [39]:
X_th = torch.tensor(X)
avg_th = torch.mean(X_th, dim=0)
avg_th

tensor([0.6328, 0.4845, 0.4141, 0.4540], dtype=torch.float64)

In [40]:
assert (X == X_th.numpy()).all()
# assert (avg_np == avg_th.numpy()).all()   # this fails alread

## 求和计算
求和运算和平均运算类似：

ta=torch.ones(5)
tc=torch.sum(ta)
tc

## 幂次计算
PyTorch下张量进行幂次计算需要使用 torch.pow 函数

In [41]:
import torch
a = torch.randn(4)
a

tensor([-1.5663,  1.1577,  0.1062,  0.4992])

In [42]:
torch.pow(a, 2)

tensor([2.4534, 1.3403, 0.0113, 0.2492])

In [43]:
torch.pow(a, torch.Tensor([2]))

tensor([2.4534, 1.3403, 0.0113, 0.2492])

## PyTorch中的广播
试试torch的广播功能：

In [44]:
t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2=torch.sqrt(t1)
t1/((t2+0.1)**2)

tensor([[0.8264, 0.8723, 0.8938],
        [0.9070, 0.9162, 0.9231]])

## element-wise运算

In [45]:
ta=torch.ones(5)
tb=torch.zeros(5)
ta-tb

tensor([1., 1., 1., 1., 1.])

In [46]:
z = torch.FloatTensor([2]).repeat(1,5)
z

tensor([[2., 2., 2., 2., 2.]])

In [47]:
z/ta

tensor([[2., 2., 2., 2., 2.]])

In [48]:
td=ta/z
td

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])

In [49]:
te=td**2
te

tensor([[0.2500, 0.2500, 0.2500, 0.2500, 0.2500]])

In [50]:
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)

In [51]:
exp

tensor([1., 2., 3., 4.])

In [52]:
a

tensor([1., 2., 3., 4.])

In [53]:
torch.pow(a, exp)

tensor([  1.,   4.,  27., 256.])

看看二维的情况：

In [54]:
t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2=t1.repeat(1,4).view(-1, 3)
t2

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

In [55]:
t3 = torch.FloatTensor([[7,8,9],[10,11,12]])
t4=t3.repeat(1,4).view(-1, 3)
t4

tensor([[ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [10., 11., 12.],
        [10., 11., 12.],
        [10., 11., 12.]])

In [56]:
SST = (t4 - t2) ** 2
SST

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]])

In [57]:
SST=torch.sum(SST,dim=0)
SST

tensor([288., 288., 288.])

## 比较大小
两个张量，element-wise比较大小

In [58]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))
torch.maximum(a, b)

tensor([3, 2, 4])

如果张量大小不同，也会默认执行广播运算

In [59]:
a = torch.tensor((1, 2, -1))
b = torch.tensor([0])
torch.maximum(a, b)

tensor([1, 2, 0])

处理NaN值
有时候会有一nan值需要处理。在torch中检测是否有nan值可以使用：x != x

In [60]:
print(np.nan==np.nan)

False


In [61]:
t5 = torch.FloatTensor([[7,np.nan,9],[10,11,12]])
t5

tensor([[ 7., nan,  9.],
        [10., 11., 12.]])

如果是直接判断一个多维张量是否有nan值，可以使用：

In [62]:
mask= t5==t5
mask

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [63]:
if len(mask[mask == True]) > 0:
    print("please check")

please check


please check

In [64]:
t6=t5[mask]
t6

tensor([ 7.,  9., 10., 11., 12.])

为了让一般的数值计算能够成为梯度可追踪的计算，我们有时候需要将常见的一些计算用tensor重写，下面是NSE的例子：

In [65]:
def nse_2d(t,p):
    seq_length = t.shape[0]
    Ngage = t.shape[1]
    tmean = torch.mean(t, dim=0)
    tmeans = tmean.repeat(seq_length, 1)
    SST = torch.sum((t - tmeans) ** 2, dim=0)
    SSRes = torch.sum((t - p) ** 2, dim=0)
    # Same as Fredrick 2019
    # temp = SSRes / ((torch.sqrt(SST) + 0.1) ** 2)
    # original NSE
    temp = SSRes / SST
    loss = torch.sum(temp) / Ngage
    return loss

t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(nse_2d(t1,t2))

tensor(0.)


tensor(0.)

# 对Tensor的操作

In [66]:
import torch

## 复制操作
类似numpy的repeat和tile，torch中可以使用repeat：

In [67]:
z = torch.FloatTensor([[1,2,3],[4,5,6]])
z.repeat(1,4)

tensor([[1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6.]])

In [68]:
z.repeat(1,4).view(-1, 3)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

In [69]:
z.repeat(4,1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]])

In [70]:
x = torch.randn(2, 3, 4)
x

tensor([[[-0.4795, -1.5400,  0.9600, -0.3700],
         [ 0.2521, -0.7870, -1.4711,  0.8187],
         [-0.4758, -1.5637, -0.6728, -1.1195]],

        [[-0.6593,  0.8593, -0.4204,  0.6079],
         [ 0.7392, -1.6754, -0.2679, -0.5868],
         [ 0.1969, -0.1451,  1.1625, -1.2838]]])

In [71]:
x[-1,:,:]

tensor([[-0.6593,  0.8593, -0.4204,  0.6079],
        [ 0.7392, -1.6754, -0.2679, -0.5868],
        [ 0.1969, -0.1451,  1.1625, -1.2838]])

In [72]:
x[-1,:,:].repeat(3,1,1)

tensor([[[-0.6593,  0.8593, -0.4204,  0.6079],
         [ 0.7392, -1.6754, -0.2679, -0.5868],
         [ 0.1969, -0.1451,  1.1625, -1.2838]],

        [[-0.6593,  0.8593, -0.4204,  0.6079],
         [ 0.7392, -1.6754, -0.2679, -0.5868],
         [ 0.1969, -0.1451,  1.1625, -1.2838]],

        [[-0.6593,  0.8593, -0.4204,  0.6079],
         [ 0.7392, -1.6754, -0.2679, -0.5868],
         [ 0.1969, -0.1451,  1.1625, -1.2838]]])

## 与numpy之间的转换

tensor 转换为numpy：

In [73]:
import torch
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


tensor([1., 1., 1., 1., 1.])

In [74]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


[1. 1. 1. 1. 1.]

In [75]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
注意tensor变化时，array也会跟着变。反过来也一样：

In [76]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 维度变换
再看看维度变换，三维变二维：

In [77]:
import torch
t1 = torch.FloatTensor([[[7,8,9],[10,11,12]],[[7,8,9],[10,11,12]]])
t1

tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [78]:
t2=t1.view(-1, 3)
t2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [79]:
t3=t1.reshape(-1, 3)
t3

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

reshape 和 view 的区别这里简单补充下，参考了：Pytorch-reshape与view的区别。Pytorch中reshape()与view()都可以改变Tensor的shape但是有略微的区别.

- view()只可以由torch.Tensor.view()来调用，view():
> 不改变Tensor数据，改变Tensor的size(即shape)
> 对于一个将要被view的Tensor，新的size必须与原来的size与stride兼容,即新的维度必须是以下两种情况:
>- 是原有维度的一个子空间
>- 只跨越原有满足邻接条件，stride[i]=stride[i+1]×size[i+1]的原有维度d,d+1,…,d+k\
> 否则，在view之前必须调用contiguous()方法，对于该方法的讨论，见StackOverflow
- reshape()可以由torch.reshape(),也可由torch.Tensor.reshape()调用。reshape():
>同样也是返回与input数据量相同，但形状不同的tensor
>若满足view的条件，则不会copy，若不满足，则会copy

## 张量转置

In [80]:
import torch
x = torch.randn(2, 3)
x

tensor([[1.5466, 0.6724, 0.6529],
        [1.4286, 2.0087, 1.1353]])

In [81]:
torch.t(x)

tensor([[1.5466, 1.4286],
        [0.6724, 2.0087],
        [0.6529, 1.1353]])