# PyTorch中的Tensor基础

PyTorch的tensor和Numpy的Array，Pandas的Series和Dataframe类似，是了解应用这些代码库的基础，这里首先简单快速地了解Tensor及其在PyTorch的作用。

主要参考：

- TENSORS
- Speed Up your Algorithms Part 1 — PyTorch
- PyTorch 101, Part 1: Understanding Graphs, Automatic Differentiation and Autograd

## 快速了解Tensor
pytorch作为NumPy的替代品，可以利用GPU的性能进行计算；可作为一个高灵活性、速度快的深度学习平台。

Tensor（张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。因此经常看到把numpy的数组包装为tensor再运算。tensor的操作和numpy中的数组操作类似，不再赘述，详见官网。下面列举一些简单例子。首先pytorch的导入是import torch，因为torch一直都是那个torch，一开始是别的语言写的，现在在python下，所以就叫pytorch。

In [1]:
import torch

Tensor是pytorch的基本数据类型：

In [2]:
x = torch.Tensor(5)
# 如果想要从tensor中获取到长度的int数据
type(list(x.shape)[0])

int

In [3]:
# 构建一个 5x3 的矩阵, 未初始化的:
x = torch.Tensor(5, 3)
x

tensor([[-1.3628e+38,  4.5726e-41, -1.3628e+38],
        [ 4.5726e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.8174e+31,  1.8788e+31,  1.7220e+22],
        [ 2.1715e-18,  8.5491e+20,  4.3205e-05]])

由此可见，PyTorch提供了Tensor，其在概念上与 numpy 数组相同，也是一个n维数组, 不过PyTorch 提供了很多能在这些 Tensor 上操作的函数

而且任何numpy 数组的操作都可以在 PyTorch Tensor 上开展。不像 numpy, PyTorch Tensor 只需将其转换为新的数据类型，就可以利用 GPU 加速他们的数字计算。

此外，tensor还拥有autograd自动求导功能。

## autograd自动求导

在PyTorch中，所有神经网络的核心是autograd包。autograd 包为张量上的所有操作提供了自动求导机制。它是一个在运行时定义（define-by-run）的框架，这意味着反向传播是根据代码如何运行来决定的，并且每次迭代可以是不同的.

torch.Tensor 是这个包的核心类。如果设置它的属性 .requires_grad 为 True，那么它将会追踪对于该张量的所有操作。当完成计算后可以通过调用 .backward()，来自动计算所有的梯度。这个张量的所有梯度将会自动累加到.grad属性.

为了阻止跟踪历史，可以使用 with torch.no_grad(): 包裹代码块，在评价模型时这很有用，因为模型可能有有参数 requires_grad=True 的能训练的参数，但是这时候我们不需要梯度。

还有一个类对于autograd的实现非常重要：Function。Tensor 和 Function 互相连接生成了一个无圈图(acyclic graph)，它编码了完整的计算历史。每个tensor有 .grad_fn 属性，该属性指向一个创建Tensor的Function。用户创建的tensor的grad_fn 是None，即新建一个tensor，它是没有grad_fn的。

如果想计算微分，可以在Tensor上调用.backward()。如果Tensor是一个标量（只含一个数据），就不需要给backward()指定参数，不过当元素较多时，需要制定一个gradient参数，这是一个有匹配shape的tensor。

上面这段话还是有点晦涩，所以看例子。先构造一个tensor，设置requires_grad=True来跟踪计算。

In [4]:
import torch
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

tensor可以做计算。

In [5]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

注意y是一个计算的结果，所以如前面文字所述，它有grad_fn属性，指向创建它的Function。

综上：

- 在PyTorch中，torch.Tensor是存储和变换数据的主要工具。
- Tensor与Numpy的多维数组非常相似。
- Tensor还提供了GPU计算和自动求梯度等更多功能，这些使Tensor更适合深度学习。